### PR TITLE
Pan & Tilt control for Sonoff camera

### PR DESCRIPTION
**Pull request by webcredo**
Pan & Tilt control option for Sonoff camera

sonoff-ptz

### CODE REVIEW

**Comment by AlexxIT** [comment]
Hi! I don't think PTZ only for one camera is good idea. We need something more customizable

**Comment by webcredo** [comment]
I think each camera will have some own specific configs to work with PTZ, as example for Sonoff device id is required. So can be possible to add more options later depend to camera.

**Comment by AlexxIT** [comment]
I think we just need to put the service call for each button in the card settings

**Comment by webcredo** [comment]
Hi, I added option to setup service call for each button.
```
        ptz:
           position: right
           opacity: 1
           actions:
              up:
               service: ...
               ...
              down:
               service: ...
               ...
              left:
               service: ...
               ...
              right:
               service: ...
               ...
```

**Comment by AlexxIT** [comment]
Great! A couple of notes:

1. As I know - some services won't pass extra params. In your example it will be `service` and `icon`.
2. iPhone 5S won't work with `?.` construction. I think these phones should still be supported
3. I think adjusting the arrow icons is not necessary. Transparency is ok.

**Comment by webcredo** [comment]
1. I excluded service & icon from service data
2. for this I think better compile js with babel it has all polyfills, other way need add lot of boilerplate conditionals to check properties existence
3. icons, opacity, position is optional properties

**Comment by AlexxIT** [comment]
I rewrote your code. I hope I made it a little easier. It lost the ability to specify icons and arrows separately. Do you think anyone will use it?

I don't want to make the code complicated, so as not to complicate its support later.

**Pull request merged**
