### PR TITLE
Fix static path config for HA 2024.7+

### LINKED ISSUE #722: 'webrtc' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop (HA 2024.7)
HA 2024.7.0b7 warns on webrtc:

```
2024-07-02 08:05:54.290 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'webrtc' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/webrtc/video-rtc.js", "/config/custom_components/webrtc/www/video-rtc.js", True)])`; This function will be removed in 2025.7 at custom_components/webrtc/__init__.py, line 63: hass.http.register_static_path("/webrtc/" + name, str(path / name)), please create a bug report at https://github.com/AlexxIT/WebRTC/issues
2024-07-02 08:05:54.329 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'webrtc' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/webrtc/embed", "/config/custom_components/webrtc/www/embed.html", True)])`; This function will be removed in 2025.7 at custom_components/webrtc/__init__.py, line 70: hass.http.register_static_path("/webrtc/embed", str(path / "embed.html")), please create a bug report at https://github.com/AlexxIT/WebRTC/issues
```

### PR DESCRIPTION
**Pull request by hmmbob**
Fixes #722 

~~Needs HA 2024.7+ (but the warning is only shown on 2024.7+ as well)~~

Tested locally, works fine

### CODE REVIEW

**Comment by Snuffy2** [comment]
I think you need to import StaticPathConfig
`from homeassistant.components.http import StaticPathConfig`

**Comment by hmmbob** [comment]
> I think you need to import StaticPathConfig `from homeassistant.components.http import StaticPathConfig`

Yeah, great catch. Did that when testing locally, forgot to add it here. Many thanks!

**Comment by AlexxIT** [comment]
Thanks. But I won't accept this because breaking previous versions. A lot of users continue to use 2023.

**Comment by hmmbob** [comment]
That's why I've updated `hacs,json` as well, so that those users will not get this new version presented.

**Comment by hmmbob** [comment]
But maybe you can leave the PR hanging around here until you're ready to raise the minimum version to a higher version and then merge, so if/when people would like to manually fix it in their config they have an idea on how-to.

**Comment by breakthestatic** [comment]
@AlexxIT, any chance this could be merged now that a backwards-compatible fix has been introduced? I tested the change locally on both a pre-2024.7 install as well as current release, 2024.8

**Comment by AlexxIT** [comment]
I need to test this before accepting.

**Comment by AlexxIT** [comment]
Thanks!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/releases/tag/v3.6.0

**Pull request merged**
