### PR TITLE
Allow rtsps urls in assertion

### PR DESCRIPTION
**Pull request by jimcortez**
This is a very simple change that allows rtsps urls to be used, it is just a change in an assertion.

### CODE REVIEW

**Comment by AlexxIT** [comment]
And they works fine?

**Comment by jimcortez** [comment]
Yeah, it at least worked in my case. Loaded rtsps stream from my ubiquity system without issue.

**Comment by AlexxIT** [comment]
Ok. Thanks. I had no idea that this protocol was supported

**Comment by iqbalaydrus** [comment]
@jimcortez how did you manage to get rtsps working? Tried using the master branch and I still got `ERROR: EOF`. Do you use unifi protect?

**Comment by allenporter** [comment]
My impression is that latest version of `vdk` needs to be pulled in to actually support RTSPS.  I added support in https://github.com/deepch/vdk/pull/41 in `vdk` however, I don't think there has been a `RTSPtoWebRTC` release yet that includes it.  @AlexxIT I suspect if you re-build a binary with a updated vdk version it will work?

**Comment by allenporter** [comment]
(i'm not sure how folks claim it was working without this fix, unless it was going through a different code path that wasn't rtsp)

**Pull request merged**
