### PR TITLE
Add shortcuts icon toggle

### PR DESCRIPTION
**Pull request by gtxaspec**
Add toggledIcon capability:

```
- name: Record
  icon: mdi:record-circle-outline
  toggledIcon: mdi:lightbulb-outline
  isToggled: false
  entity: binary_sensor.example
  service: switch.toggle
  service_data:
    entity_id: switch.camera_record
 ```

### CODE REVIEW

**Comment by AlexxIT** [comment]
I don't think this is good idea because we don't know start state. Service may be toggle from different start state and icon will be wrong.

**Comment by gtxaspec** [comment]
@AlexxIT 
the user can set the start state:
`  isToggled: false` or `  isToggled: true`

**Comment by gtxaspec** [comment]
@AlexxIT I added support for `entity: binary_sensor.example`, and i tested reading the state, it works well.

**Comment by pcmike** [comment]
> @AlexxIT I added support for `entity: binary_sensor.example`, and i tested reading the state, it works well.

Does this only work for binary_sensor? What about input_boolean?

**Pull request closed without merging**
