### PR TITLE
Add video wrapper for ptz transforms for compatibility with rotations

### PR DESCRIPTION
**Pull request by dbuezas**
Solves incompatibility with rotated video.

Reported in:
* https://github.com/AlexxIT/WebRTC/issues/21#issuecomment-1631418967
* https://github.com/dbuezas/pan-zoom-controller/issues/1

### CODE REVIEW

**Comment by AlexxIT** [comment]
Are you sure construction `...` can pass ESLint?

**Comment by dbuezas** [comment]
Safari support:
* [DomPoint](https://caniuse.com/?search=DOMPoint) on Safari 10.1
* [DomMatrix](https://caniuse.com/?search=DomMatrix) on Safari 11 (it was called WebKitCSSMatrix before)

**Comment by dbuezas** [comment]
> Are you sure construction `...` can pass ESLint?

It shouldn't be an issue: https://caniuse.com/mdn-javascript_operators_spread_spread_in_function_calls

**Comment by gtxaspec** [comment]
+1 for this, solves video rotation not working with PTZ enabled =D

**Comment by gtxaspec** [comment]
@dbuezas I applied these changes manually, and rotation + ptz works in Firefox but not Chrome Beta... Version 115.0.5790.98 (Official Build) beta (64-bit)... wondering if you can test or if it's just me.

**Comment by AlexxIT** [comment]
@dbuezas maybe it's easier to implement rotation param for card. So users shouldn't use custom style for that

**Comment by dbuezas** [comment]
I use chrome and the android app and it works for me. Maybe you haven't cleared cache?

Regarding styling in general, I also use it myself to cut a video in half in a "double lense" camera, so it is quite useful to have it IMO

**Comment by gtxaspec** [comment]
> I use chrome and the android app and it works for me. Maybe you haven't cleared cache?
> 
> Regarding styling in general, I also use it myself to cut a video in half in a "double lense" camera, so it is quite useful to have it IMO

You're right! My mistake, it works well!

**Comment by AlexxIT** [comment]
Thanks!

**Comment by dbuezas** [comment]
I'm not sure if I left a comment on how the heck this works, so here it is:
* the user rotated/skewed/cropped (transformed) the video via css
* The digital ptz needs to know if the browser added black bars to center the video while in full screen, so the same place is zoomed
* this picks the transform the user did and the original aspect ratio of the video, and figures out the aspect ratio of the bounding box of the transformed video
* with that and the dimensions of the screen, this figures out where the browser added black bars to center the video
* Now it can finally ensure that zoom and pan are consistent between the full screen and normal players

**Comment by dbuezas** [comment]
Oh, and adds a wrapper element around the video so it can manipulate it without interfering with the user styles

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/releases/tag/v3.3.0

**Pull request merged**
